services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elk_es01
    restart: on-failure
    volumes:
      - vol_elastic:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "cluster.name=adm_videos_cluster"
      - "node.name=codeflix"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - ntw_elastic

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    container_name: kfk_zookeeper
    ports:
      - '2181:2181'
    networks:
      - ntw_kafka

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kfk_kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
        - ntw_kafka
    volumes:
      - vol_kafka:/var/lib/kafka/data

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    container_name: kfk_control_center
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - '9021:9021'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
        - ntw_kafka

  kafka-connect:
    image: confluentinc/cp-kafka-connect:6.0.0
    container_name: kfk_connect
    depends_on:
      - kafka
    ports:
      - '8083:8083'
    networks:
      - ntw_kafka
      - ntw_app
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,data/connect-jars
    volumes:
      - vol_kconnect:/data
    command:
      - bash
      - -c
      - |
        echo "Installing plugins"
        confluent-hub install --no-prompt debezium/debezium-connector-mysql:1.2.2
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  vol_elastic:
      name: vol_elastic
      external: true
  vol_kafka:
      name: vol_kafka
      external: true
  vol_kconnect:
      name: vol_kconnect
      external: true

networks:
    ntw_elastic:
        name: ntw_elastic
        external: true
    ntw_kafka:
        name: ntw_kafka
        external: true
    ntw_app:
        name: ntw_app
        external: true

