services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elk_es01
    restart: on-failure
    volumes:
      - vol_elastic:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "cluster.name=adm_videos_cluster"
      - "node.name=codeflix"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - ntw_elastic

volumes:
  vol_elastic:
      name: vol_elastic

networks:
    ntw_elastic:
        name: ntw_elastic
        external: true
