name: CI Pipeline

# Pipeline trigger
on:
  # The pipeline will run whenever there is a push to the main or master branches
#  push:
#    branches:
#      - main
#      - master
  # Enable manual trigger through the GitHub Actions interface
  workflow_dispatch:

jobs:
  # Test execution job
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Steps configuration of our job
    steps:
      # 1. The actions/checkout@v3 step checks out your repository code so your workflow can access it.
      - uses: actions/checkout@v3

      # 2. Configure the JDK on the machine. It is used to set up Java JDK. Version 17 is used.
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

        # 3. Configure Cache Maven packages. It is used to cache dependencies and build outputs to improve workflow execution time.
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2                                               # path: This sets the path of the directory you want to cache. In the context of a Maven project, ~/.m2 refers to the local Maven repository which is stored in the user's home directory. This is where all the project dependencies are downloaded to. By caching this directory, the build times can be significantly reduced as the dependencies don't need to be re-downloaded with every build.
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}   # key: The cache key is a unique identifier for the cache. GitHub Actions uses the key to save or restore a cache. In this case, the cache key is created using the runner's OS (${{ runner.os }}) and -m2- followed by a hash of all pom.xml files (${{ hashFiles('**/pom.xml') }}). This hash function ensures that if any of the pom.xml files are changed (indicating that possibly the dependencies have changed) a new cache key will be generated and a new cache will be created.
          restore-keys: ${{ runner.os }}-m2                         # restore-keys: The restore-keys option provides a list of keys to use when the key doesn't hit an existing cache key. If there are no matches with the key, the action will search for keys in restore-keys. In this case, it will fallback to the cache key for the runner's OS ${{ runner.os }}-m2. This can improve performance by restoring a partial cache when the dependencies in pom.xml files change.

      # 3. Check if Maven is installed
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      # 4. Build the application with Maven. The -B option in maven command is for batch mode, making the build output less verbose.
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 5. Run the application tests. The -B option in maven command is for batch mode, making the build output less verbose.
      - name: Run application tests with Maven
        run: mvn -B test --file ./pom.xml